# Generated by Django 4.2.16 on 2026-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(db_index=True, max_length=120)),
                ('content', models.TextField()),
                ('outgoing', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sent_time'],
            },
        ),
        migrations.CreateModel(
            name='IssuanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('student_id', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('invitation_msg_id', models.CharField(db_index=True, max_length=120)),
                ('invitation_url', models.TextField(blank=True)),
                ('connection_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('cred_ex_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('state', models.CharField(default='awaiting_scan', max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerArtifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=255)),
                ('cred_def_id', models.CharField(max_length=255)),
                ('issuer_did', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ledger artifacts',
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_ex_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('invitation_url', models.TextField(blank=True)),
                ('state', models.CharField(default='pending', max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
