# Generated by Django 4.2.16 on 2026-07-23 06:53

from django.db import migrations, models
import ssi.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancerequest',
            name='invitation_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='issuancerequest',
            name='token',
            field=models.CharField(db_index=True, default=ssi.models.short_token, max_length=32),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='invitation_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loginsession',
            name='token',
            field=models.CharField(db_index=True, default=ssi.models.short_token, max_length=32),
        ),
    ]
