# Generated by Django 4.2.16 on 2026-07-23 12:12

from django.db import migrations, models
import ssi.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0002_issuancerequest_invitation_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Faculty', max_length=120)),
                ('invitation_msg_id', models.CharField(db_index=True, max_length=120)),
                ('invitation_url', models.TextField(blank=True)),
                ('invitation_json', models.JSONField(blank=True, default=dict)),
                ('token', models.CharField(db_index=True, default=ssi.models.short_token, max_length=32)),
                ('connection_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('their_label', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(default='awaiting_scan', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
