# Generated by Django 4.2.16 on 2026-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0003_chatinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancerequest',
            name='role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
