# Generated by Django 4.2.16 on 2026-07-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0006_security_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinvitation',
            name='pres_ex_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
