# Generated by Django 4.2.16 on 2026-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0007_chatinvitation_pres_ex_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('id_number', models.CharField(max_length=60, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('issued', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
