# Generated by Django 4.2.16 on 2026-07-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0009_memberrecord_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatinvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='chatinvitation',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='chatinvitation',
            name='owner_id_number',
        ),
        migrations.RemoveField(
            model_name='chatinvitation',
            name='pres_ex_id',
        ),
        migrations.RemoveField(
            model_name='chatinvitation',
            name='their_label',
        ),
        migrations.AddField(
            model_name='chatinvitation',
            name='faculty_id_number',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='chatinvitation',
            name='student_id_number',
            field=models.CharField(db_index=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='chatinvitation',
            name='initiated_by_role',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
