# Generated by Django 4.2.16 on 2026-07-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0010_messaging_mutual_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinvitation',
            name='portal_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
