# Generated by Django 4.2.16 on 2026-07-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssi', '0012_chat_dual_connection_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatinvitation',
            name='counterparty_invitation_json',
        ),
        migrations.RemoveField(
            model_name='chatinvitation',
            name='counterparty_invitation_msg_id',
        ),
        migrations.RemoveField(
            model_name='chatinvitation',
            name='counterparty_invitation_url',
        ),
        migrations.RemoveField(
            model_name='chatinvitation',
            name='counterparty_token',
        ),
    ]
